In [1]:
import numpy as np

# 通用函数

## 一元函数：


        函数                                                       描述

        np.abs                                                    绝对值 
        np.sqrt                                                    开根 
        np.square                                                  平方 
        np.exp                                                  计算指数(e^x) 
        np.log，np.log10，np.log2，np.log1p        求以e为底，以10为低，以2为低，以(1+x)为底的对数 
        np.sign                                   将数组中的值标签化，大于0的变成1，等于0的还是0，小于0的变成-1 
        np.ceil                                   朝着无穷大的方向取整，比如5.1会变成6，-6.3会变成-6 
        np.floor                                  朝着负无穷大方向取证，比如5.1会变成5，-6.3会变成-7 
        np.rint，np.round                                     返回四舍五入后的值 
        np.modf                                       将整数和小数分隔开来形成两个数组 
        np.isnan                                                判断是否是nan 
        np.isinf                                                判断是否是inf 
        np.cos，np.cosh，np.sin，np.sinh，np.tan，np.tanh            三角函数 
        np.arccos，np.arcsin，np.arctan                            反三角函数 


In [3]:
a = np.random.uniform(-10, 10, size=(3,5))
print(a)

[[-6.4062641   5.93380205 -1.23429029  4.58653456 -4.68457809]
 [ 6.81126537  0.44264164  5.80108833 -7.41264647 -4.55589217]
 [-3.9033839   8.70968194  3.28034325  7.98252149  0.81938142]]


In [4]:
# np.abs 
print(np.abs(a))

[[6.4062641  5.93380205 1.23429029 4.58653456 4.68457809]
 [6.81126537 0.44264164 5.80108833 7.41264647 4.55589217]
 [3.9033839  8.70968194 3.28034325 7.98252149 0.81938142]]


In [5]:
# np.sqrt
# 注意负数开根号会变成NAN值
print(np.sqrt(a))

[[       nan 2.43593966        nan 2.14161961        nan]
 [2.6098401  0.66531319 2.40854486        nan        nan]
 [       nan 2.95121703 1.81117179 2.82533564 0.90519689]]


/var/sw/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [6]:
# np.square
print(np.square(a))

[[41.04021976 35.21000674  1.52347251 21.03629926 21.94527184]
 [46.39333588  0.19593162 33.6526258  54.94732766 20.75615348]
 [15.23640588 75.85855951 10.76065181 63.72064929  0.6713859 ]]


In [7]:
# np.exp
print(np.exp(a))

[[1.65118164e-03 3.77587394e+02 2.91041245e-01 9.81536942e+01
  9.23663085e-03]
 [9.08019056e+02 1.55681433e+00 3.30659230e+02 6.03571247e-04
  1.05051237e-02]
 [2.01735306e-02 6.06131432e+03 2.65848963e+01 2.92930797e+03
  2.26909578e+00]]


In [14]:
# np.log
print(np.log(a))
print(np.log10(a))
print(np.log2(a))
print(np.log1p(a))

[[        nan  1.78066516         nan  1.52312474         nan]
 [ 1.91857791 -0.81499478  1.75804554         nan         nan]
 [        nan  2.16443527  1.18794806  2.07725434 -0.19920559]]
[[        nan  0.77333305         nan  0.66148467         nan]
 [ 0.8332278  -0.35394773  0.76350948         nan         nan]
 [        nan  0.9400023   0.51591929  0.9021401  -0.08651389]]
[[        nan  2.5689568          nan  2.19740451         nan]
 [ 2.76792284 -1.17578892  2.53632359         nan         nan]
 [        nan  3.12262004  1.71384678  2.99684453 -0.28739292]]
[[       nan 1.9364083         nan 1.72035916        nan]
 [2.05556697 0.3664759  1.91708265        nan        nan]
 [       nan 2.27312353 1.4540332  2.19528063 0.59849656]]


/var/sw/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  
/var/sw/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log10
  This is separate from the ipykernel package so we can avoid doing imports until
/var/sw/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in log2
  after removing the cwd from sys.path.
/var/sw/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log1p
  """


In [15]:
# np.sign
print(np.sign(a))

[[-1.  1. -1.  1. -1.]
 [ 1.  1.  1. -1. -1.]
 [-1.  1.  1.  1.  1.]]


In [17]:
# np.ceil 朝正无穷大的方向取整, 就是变大了
print(np.ceil(a))

[[-6.  6. -1.  5. -4.]
 [ 7.  1.  6. -7. -4.]
 [-3.  9.  4.  8.  1.]]


In [19]:
# np.floor 朝负无穷大的方向取整，就是变小了
print(np.floor(a))

[[-7.  5. -2.  4. -5.]
 [ 6.  0.  5. -8. -5.]
 [-4.  8.  3.  7.  0.]]


In [20]:
# np.rint 或者 np.round
print(np.rint(a))
print(np.round(a))

[[-6.  6. -1.  5. -5.]
 [ 7.  0.  6. -7. -5.]
 [-4.  9.  3.  8.  1.]]
[[-6.  6. -1.  5. -5.]
 [ 7.  0.  6. -7. -5.]
 [-4.  9.  3.  8.  1.]]


In [22]:
# np.modf 注意会切割成两个数组！！！！！！
print(np.modf(a))

(array([[-0.4062641 ,  0.93380205, -0.23429029,  0.58653456, -0.68457809],
       [ 0.81126537,  0.44264164,  0.80108833, -0.41264647, -0.55589217],
       [-0.9033839 ,  0.70968194,  0.28034325,  0.98252149,  0.81938142]]), array([[-6.,  5., -1.,  4., -4.],
       [ 6.,  0.,  5., -7., -4.],
       [-3.,  8.,  3.,  7.,  0.]]))


In [25]:
# np.isnan
print(np.isnan(a))

[[False False False False False]
 [False False False False False]
 [False False False False False]]


In [24]:
# np.isinf 判断是否是INF值，就是正负无穷大的值
print(np.isinf(a))

[[False False False False False]
 [False False False False False]
 [False False False False False]]


In [27]:
# np.cos，np.cosh，np.sin，np.sinh，np.tan，np.tanh  
print(np.sin(a))

[[-0.12276829 -0.34231839 -0.9439141  -0.99209078  0.9996133 ]
 [ 0.50387587  0.428328   -0.46363817 -0.90418216  0.98777935]
 [ 0.6902187   0.65568992 -0.13830582  0.99175012  0.73072368]]


In [29]:
# np.arccos，np.arcsin，np.arctan
print(np.arcsin(a))

[[      nan       nan       nan       nan       nan]
 [      nan 0.4585425       nan       nan       nan]
 [      nan       nan       nan       nan 0.9603311]]


/var/sw/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in arcsin
  


## 二元函数：


        函数                                                            描述

        np.add                                                 加法运算（即1+1=2），相当于+ 
        np.subtract                                            减法运算（即3-2=1），相当于- 
        np.negative                                            负数运算（即-2），相当于加个负号 
        np.multiply                                            乘法运算（即2*3=6），相当于* 
        np.divide                                              除法运算（即3/2=1.5），相当于/ 
        np.floor_divide                                        取整运算，相当于// 
        np.mod                                                 取余运算，相当于% 
        greater,greater_equal,less,less_equal,equal,not_equal  >,>=,<,<=,=,!= 的函数表达式 
        logical_and                                            & 的函数表达式 
        logical_or                                             | 的函数表达式 


In [32]:
# 可以用运算符直接进行计算, 实际上运算符（+-×/）就是函数的语法糖，可以让代码更简单一些
print(a+1)

[[-5.4062641   6.93380205 -0.23429029  5.58653456 -3.68457809]
 [ 7.81126537  1.44264164  6.80108833 -6.41264647 -3.55589217]
 [-2.9033839   9.70968194  4.28034325  8.98252149  1.81938142]]


In [34]:
# np.add
print(np.add(a, 1))

[[-5.4062641   6.93380205 -0.23429029  5.58653456 -3.68457809]
 [ 7.81126537  1.44264164  6.80108833 -6.41264647 -3.55589217]
 [-2.9033839   9.70968194  4.28034325  8.98252149  1.81938142]]


In [35]:
# np.subtract
print(np.subtract(a, 2))

[[-8.4062641   3.93380205 -3.23429029  2.58653456 -6.68457809]
 [ 4.81126537 -1.55735836  3.80108833 -9.41264647 -6.55589217]
 [-5.9033839   6.70968194  1.28034325  5.98252149 -1.18061858]]


In [36]:
# np.negative 直接加负号
print(np.negative(a))

[[ 6.4062641  -5.93380205  1.23429029 -4.58653456  4.68457809]
 [-6.81126537 -0.44264164 -5.80108833  7.41264647  4.55589217]
 [ 3.9033839  -8.70968194 -3.28034325 -7.98252149 -0.81938142]]


In [40]:
# np.multiply 
print(np.multiply(a, -2))

[[ 12.81252821 -11.8676041    2.46858057  -9.17306912   9.36915617]
 [-13.62253073  -0.88528328 -11.60217666  14.82529294   9.11178434]
 [  7.8067678  -17.41936388  -6.56068649 -15.96504297  -1.63876283]]


In [41]:
# np.divide
print(np.divide(a, 0))

[[-inf  inf -inf  inf -inf]
 [ inf  inf  inf -inf -inf]
 [-inf  inf  inf  inf  inf]]


/var/sw/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [44]:
# np.floor_divide 地板除，取整
print(np.floor_divide(a, 2))
print(a // 2)

[[-4.  2. -1.  2. -3.]
 [ 3.  0.  2. -4. -3.]
 [-2.  4.  1.  3.  0.]]
[[-4.  2. -1.  2. -3.]
 [ 3.  0.  2. -4. -3.]
 [-2.  4.  1.  3.  0.]]


In [58]:
# np.mod 取余 
print(np.mod(a, 2))
print(a % 2)

[[1.5937359  1.93380205 0.76570971 0.58653456 1.31542191]
 [0.81126537 0.44264164 1.80108833 0.58735353 1.44410783]
 [0.0966161  0.70968194 1.28034325 1.98252149 0.81938142]]
[[1.5937359  1.93380205 0.76570971 0.58653456 1.31542191]
 [0.81126537 0.44264164 1.80108833 0.58735353 1.44410783]
 [0.0966161  0.70968194 1.28034325 1.98252149 0.81938142]]


In [65]:
# greater,greater_equal,less,less_equal,equal,not_equal  注意返回值是True或False
print(np.greater(a,0))
print(a > 0)
print(a[a > 0])# 利用判断条件进行切片
print(a[np.greater(a,0)])

[[False  True False  True False]
 [ True  True  True False False]
 [False  True  True  True  True]]
[[False  True False  True False]
 [ True  True  True False False]
 [False  True  True  True  True]]
[5.93380205 4.58653456 6.81126537 0.44264164 5.80108833 8.70968194
 3.28034325 7.98252149 0.81938142]
[5.93380205 4.58653456 6.81126537 0.44264164 5.80108833 8.70968194
 3.28034325 7.98252149 0.81938142]


In [81]:
# logical_and 注意返回值是True或False
print(np.logical_and(a>0, a<5))
print((a>0) & (a<5))

[[False False False  True False]
 [False  True False False False]
 [False False  True False  True]]
[[False False False  True False]
 [False  True False False False]
 [False False  True False  True]]


In [80]:
# logical_or 注意返回值是True或False
print(np.logical_or(a>0, a<5))
print((a>0) | (a<5))

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


## 聚合函数：


        函数名称                 NAN安全                 版本描述

        np.sum                np.nansum              计算元素的和 
        np.prod               np.nanprod             计算元素的积 
        np.mean               np.nanmean             计算元素的平均值 
        np.std                np.nanstd              计算元素的标准差 
        np.var                np.nanvar              计算元素的方差 
        np.min                np.nanmin              计算元素的最小值 
        np.max                np.nanmax              计算元素的最大值 
        np.argmin             np.nanargmin           找出最小值的索引 
        np.argmax             np.nanargmax           找出最大值的索引 
        np.median             np.nanmedian           计算元素的中位数 


In [85]:
# np.sum
print(np.sum(a, axis=0))

[-3.49838264 15.08612563  7.84714129  5.15640958 -8.42108884]


In [86]:
# np.prod
print(np.prod(a, axis=0))

[ 170.32323851   22.87639653  -23.48800219 -271.3926328    17.48759266]


In [88]:
# np.mean
print(np.mean(a))

1.0780136675609464


In [90]:
# np.std 标准差
print(np.std(a))

5.326140534812175


In [92]:
# np.var
print(np.square(np.std(a)))# 标准差的平方就是方差
print(np.var(a))

28.367772996569318
28.36777299656932


In [94]:
# np.argmax, np.argmin 注意索引还是从0开始！！！！
print(np.argmax(a, axis=0))
print(np.argmin(a, axis=1))

[1 2 1 2 2]
[0 3 0]


In [97]:
# np.median 注意中位数是将数组先按数值排大小后，再选择位于数组最中间的那个数，如果数组的数量是偶数就用最中间的两个数除以2得到
# 所以中位数不一定是数组里的数！！！
print(np.median(a, axis=0))
print(np.median(a, axis=1))

[-3.9033839   5.93380205  3.28034325  4.58653456 -4.55589217]
[-1.23429029  0.44264164  3.28034325]


### 同样 Python 中也内置了 sum 函数，但是Python内置的 sum 函数执行效率没有 np.sum 那么高，差距极大！

In [142]:
# 使用python内置的函数sum
%time  print(sum(np.arange(1000000)))

499999500000
CPU times: user 520 ms, sys: 0 ns, total: 520 ms
Wall time: 527 ms


In [134]:
# 使用numpy.sum
%time  print(np.sum(np.arange(1000000)))

499999500000
CPU times: user 2.17 ms, sys: 184 µs, total: 2.35 ms
Wall time: 2.06 ms


## 布尔数组的函数


        函数名称             描述

        np.any       验证任何一个元素是否为真 
        np.all       验证所有元素是否为真 


In [146]:
# 比如想看下数组中是不是所有元素都为0
b = np.arange(10)
print(b.all())
# 再比如我们想要看数组中是否有等于0的数
print(b.any())

False
True


In [149]:
print((a>0).all())
print((a>0).any())

False
True


In [151]:
print(np.all(a>0))
print(np.any(a>0))

False
True


## 排序：
- np.sort ：
    - 指定轴进行排序。默认是使用数组的最后一个轴进行排序。
    - 还有 ndarray.sort() ，这个方法会直接影响到原来的数组，而不是返回一个新的排序后的数组。
- np.argsort ：
    - 返回排序后的索引下标值。
- 降序排序： 
    - np.sort 默认会采用升序排序。
    - 如果我们想采用降序排序，那么可以采用以下方案来实现：
        - 使用负号
            - np.sort(-a)
        - 使用sort和argsort以及take
            - indexes = np.argsort(-a) #排序后的结果就是降序的
            - np.take(a,indexes) #从a中根据下标提取相应的元素
            

In [155]:
# np.sort
print(np.sort(a))# 如果没有指定轴，则默认以最里面的轴进行排序，即axis=1
print(np.sort(a, axis=0))
print(a)# 此方法不会更改数组本身！！！

[[-6.4062641  -4.68457809 -1.23429029  4.58653456  5.93380205]
 [-7.41264647 -4.55589217  0.44264164  5.80108833  6.81126537]
 [-3.9033839   0.81938142  3.28034325  7.98252149  8.70968194]]
[[-6.4062641   0.44264164 -1.23429029 -7.41264647 -4.68457809]
 [-3.9033839   5.93380205  3.28034325  4.58653456 -4.55589217]
 [ 6.81126537  8.70968194  5.80108833  7.98252149  0.81938142]]
[[-6.4062641   5.93380205 -1.23429029  4.58653456 -4.68457809]
 [ 6.81126537  0.44264164  5.80108833 -7.41264647 -4.55589217]
 [-3.9033839   8.70968194  3.28034325  7.98252149  0.81938142]]


In [163]:
# ndarray.sort()
b = np.random.randint(10, size=(3,5))
print(b)
print(b.sort(axis=0))# 注意此方法无返回值，直接修改原数组
print(b)

[[6 9 2 6 9]
 [8 4 9 5 3]
 [4 2 4 5 0]]
None
[[4 2 2 5 0]
 [6 4 4 5 3]
 [8 9 9 6 9]]


In [166]:
# np.argsort
print(np.argsort(a, axis=0))# 注意返回的是从小到大排列后的索引值（从0开始）

[[0 1 0 1 0]
 [2 0 2 0 1]
 [1 2 1 2 2]]


In [185]:
# 降序排序
# 1.加负号，加两次，就变成原数组从大到小排序了
print(-np.sort(-a))

[[ 5.93380205  4.58653456 -1.23429029 -4.68457809 -6.4062641 ]
 [ 6.81126537  5.80108833  0.44264164 -4.55589217 -7.41264647]
 [ 8.70968194  7.98252149  3.28034325  0.81938142 -3.9033839 ]]


In [187]:
# 降序排序
# 2.使用sort和argsort以及take
indexs = np.argsort(-a)# 此时相当于是降序排序的索引


## 其他函数补充：
- np.apply_along_axis ：
    - 沿着某个轴执行指定的函数.
- np.linspace ：
    - 用来将指定区间内的值平均分成多少份
- np.unique ：
    - 返回数组中的唯一值, 并且会返回每个唯一值出现的次数。

In [188]:
c = np.random.randint(100, size=(3,20))
print(c)

[[98 37 67 27 89  7 43 96 52 63 59 37 54 45 97 19 35 54  8 60]
 [62  8 37 63 79 39 15 18 54 55 28 17 59 85 15 20 43 21 78 45]
 [28 13 84 88 27 49 22 41 23 92 34  4 72 50 83 16 10 59 24 42]]


In [196]:
# np.apply_along_axis 可以沿着某个轴执行函数
def get_mean(x):
    y = x[(x!=np.max(x)) & (x!=np.min(x))].mean()# 去除最大值和最小值后取平均值
#     print(y)
#     print("====" * 20)
    return y
print(np.apply_along_axis(get_mean, axis=1, arr=c))# 对c数组中的每一行(axis=1)执行get_mean()函数

[52.33333333 41.55555556 42.5       ]


In [203]:
# 使用lambda匿名函数
print(np.apply_along_axis(lambda x: x[(x!=np.max(x)) & (x!=np.min(x))].mean(), axis=1, arr=c))

[52.33333333 41.55555556 42.5       ]


In [211]:
# np.linspace 用来将指定区间内的值平均分成多少份
# 注意这个函数里的取值区间是-----------------------------------------------左右都包括的！！！！！！
# 注意这个函数里的取值区间是-----------------------------------------------左右都包括的！！！！！！
# 注意这个函数里的取值区间是-----------------------------------------------左右都包括的！！！！！！
print(np.linspace(0, 10, 11))# 将包含0~10区间内的值平均等分成11份
print(np.linspace(1, 10, 10))# 将包含1~10区间内的值平均等分成10份

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [222]:
# np.unique 返回数组中的唯一值, 并且会返回每个唯一值出现的次数
d = np.random.randint(10, size=(3,5))
print(d)
print(np.unique(d))# 返回数组中的唯一值
print(np.unique(d, return_counts=True))# 返回数组中的唯一值, 并且返回每个唯一值出现的次数

[[4 4 6 9 0]
 [9 0 8 3 5]
 [3 8 9 5 1]]
[0 1 3 4 5 6 8 9]
(array([0, 1, 3, 4, 5, 6, 8, 9]), array([2, 1, 2, 2, 2, 1, 2, 3]))


### 更多：
- https://docs.scipy.org/doc/numpy/reference/index.html