# Numpy练习题

## 一、查看Numpy的版本号

In [1]:
# 1.
import numpy as np
print(np.__version__)

1.17.4


## 二、如何创建一个所有值都是False的布尔类型的数组

In [2]:
# 2.1
a = np.zeros((4,5), dtype=np.bool)
print(a)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [3]:
# 2.2
a = np.full((4,5), True, dtype=np.bool)
print(a)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


## 三、将一个有10个数的数组的形状进行转换

In [4]:
# 3.1
a = np.arange(10)
b = a.reshape((2,5))
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
# 3.2
a = np.arange(10)
# 转换成 n行一列 的二维数组
b = a[:,np.newaxis]# 转换成(10,1)的数组，新方法

print(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [6]:
# 上面的 np.newaxis 所处的位置，会变成1。比如：
a = np.random.randint(10, size=(3,5))
a1 = a[:,np.newaxis,:]
print(a1.shape)# 结果是(3,1,5)，因为np.newaxis所在的位置是1

(3, 1, 5)


## 四、将数组中所有偶数都替换成0（改变原来数组和不改变原来数组两种方式实现）

In [7]:
# 4.1 改变原数组
a = np.random.randint(10, size=(3,5))
print(a)
a[a % 2 == 0] = 0
print(a)

[[8 7 8 0 6]
 [3 9 0 3 4]
 [2 4 2 9 8]]
[[0 7 0 0 0]
 [3 9 0 3 0]
 [0 0 0 9 0]]


In [8]:
# 4.2 不改变原数组
a = np.random.randint(10, size=(3,5))
print(np.where(a%2==0, 0, a))
print(a)

[[0 0 0 5 5]
 [5 0 0 7 1]
 [3 0 7 0 3]]
[[6 6 6 5 5]
 [5 2 6 7 1]
 [3 2 7 2 3]]


## 五、创建一个一维且有10个数的数组，元素是从 0-1 之间，但是不包含0和1

In [9]:
# 5.1
a = np.random.rand(10)# 这里虽然包含0，但取到完全是0值的概率基本为0
print(a)

[0.85972976 0.08206368 0.73061837 0.87582341 0.19696641 0.40545831
 0.98799372 0.48864226 0.14157156 0.40902747]


In [10]:
# 5.2 
# 注意linspace是等分的，所以取12个值，抛去开头和结尾的值剩下的10个值必然不包含0和1
print(np.linspace(0,1,12)[1:-1])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## 六、求以下数组大于等于5并且小于等于10的数组
- a = np.arange(15)

In [11]:
# 6.1
a = np.arange(15)
print(a[(a>=5) & (a<=10)])

[ 5  6  7  8  9 10]


In [12]:
# 6.2
a = np.arange(15)
print(a[np.logical_and(a>=5, a<=10)])

[ 5  6  7  8  9 10]


In [13]:
# 6.3
a = np.arange(15)
index = np.where((a>=5) & (a<=10))
print(a[index])

[ 5  6  7  8  9 10]


## 七、将一个二维数组的行和列分别进行逆向

In [14]:
# 7
a = np.random.randint(10, size=(3,5))
print(a)
print(a[::-1])# 对行进行逆向
print(a[:, ::-1])# 对列进行逆向
print(a[::-1, ::-1])# 对行列都进行逆向
print(a.T)# 这是转置
print(a)

[[4 4 0 4 1]
 [3 9 9 3 3]
 [7 2 9 4 3]]
[[7 2 9 4 3]
 [3 9 9 3 3]
 [4 4 0 4 1]]
[[1 4 0 4 4]
 [3 3 9 9 3]
 [3 4 9 2 7]]
[[3 4 9 2 7]
 [3 3 9 9 3]
 [1 4 0 4 4]]
[[4 3 7]
 [4 9 2]
 [0 9 9]
 [4 3 4]
 [1 3 3]]
[[4 4 0 4 1]
 [3 9 9 3 3]
 [7 2 9 4 3]]


## 八、如何将科学计数法转换为浮点类型打印

In [15]:
# 8
# set_printoptions用来设置打印的时候的一些配置和选项
# 将suppress设置为True，就不会显示成科学计数法了，并且通过precision来控制小数点后要保留几位
np.set_printoptions(suppress=True, precision=8)
a = np.random.rand(3,5)/1e1
print(a)
# help(np.set_printoptions)

[[0.00921615 0.0472691  0.00915681 0.06783558 0.02752529]
 [0.06444871 0.03731267 0.0801772  0.00996459 0.05288384]
 [0.03954653 0.06802426 0.08015224 0.01540668 0.05111305]]


## 九、获取一个数组中唯一的元素
## 十、获取一个数组中唯一的元素个数的排行

In [16]:
# 9
# 10
a = np.random.randint(10, size=(3,6))
print(a)
print(np.unique(a, return_counts=True))# 返回数组中唯一的元素并打印其出现的次数

[[1 4 7 3 2 0]
 [4 6 9 3 7 8]
 [3 3 6 0 8 4]]
(array([0, 1, 2, 3, 4, 6, 7, 8, 9]), array([2, 1, 1, 4, 3, 2, 2, 2, 1]))


## 十一、如何找到数组中每行的最大值

In [17]:
# 11.1
a = np.random.randint(10, size=(6,5))
print(a)
print(np.max(a,axis=1))

[[2 6 6 7 6]
 [7 0 0 1 0]
 [3 0 0 1 3]
 [9 2 3 2 9]
 [3 9 5 1 4]
 [3 4 7 0 7]]
[7 7 3 9 9 7]


In [18]:
# 11.2
print(a)
print(np.apply_along_axis(lambda x: np.max(x), axis=1, arr=a))

[[2 6 6 7 6]
 [7 0 0 1 0]
 [3 0 0 1 3]
 [9 2 3 2 9]
 [3 9 5 1 4]
 [3 4 7 0 7]]
[7 7 3 9 9 7]


## 十二、如何按照行求最小值与最大值相除的结果

In [19]:
# 12.1
a = np.random.randint(1, 10, size=(7,5))
print(a)
print(np.min(a, axis=1) / np.max(a, axis=1))

[[5 1 7 7 5]
 [7 9 5 4 4]
 [5 1 9 7 3]
 [6 2 1 1 2]
 [8 9 6 7 7]
 [6 4 2 7 2]
 [3 9 3 1 7]]
[0.14285714 0.44444444 0.11111111 0.16666667 0.66666667 0.28571429
 0.11111111]


In [20]:
# 12.2
print(np.apply_along_axis(lambda x: np.min(x)/np.max(x), axis=1, arr=a))

[0.14285714 0.44444444 0.11111111 0.16666667 0.66666667 0.28571429
 0.11111111]


In [21]:
# 12.3 答案
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(np.apply_along_axis(lambda x: np.min(x)/np.max(x),arr=a,axis=1))

[0.44444444 0.125      0.5        1.         0.11111111]


## 十三、判断两个数组是否完全相等

In [22]:
a = np.random.randint(1, 10, size=(3,5))
b = np.random.randint(1, 10, size=(3,5))
print(np.all(a == b))
print((a == b).all())

False
False


## 十四、找到数组中离某个元素的最近的值

In [23]:
# 14
np.random.seed(10)
a = np.random.uniform(1, 10, 20)# 一个一维数组
print(a)
A = 2.8 # 某个元素
print(a[np.abs(A - a).argmin()])

[7.94188579 1.18676754 6.70283411 7.73923494 5.48656311 3.02316981
 2.78256578 7.84477641 2.52199753 1.79505833 7.16823837 9.58054012
 1.0355344  5.60973037 8.31358865 6.5127346  7.49579786 3.62688461
 9.2599671  7.43118205]
2.782565782836616


## 十五、设置一个数组不能修改值

In [24]:
# 15
a = np.full((2,2), 3)
a.flags.writeable = False# 注意，np.flags.writeable 属性默认为True，当为False时是不可写入的状态，即只能读取
a[0] = 1
# help(np.ndarray.flags)

ValueError: assignment destination is read-only