In [1]:
import numpy as np

## 深拷贝和浅拷贝
- 在操作数组的时候，它们的数据有时候拷贝进一个新的数组，有时候又不是。这经常是初学者感到困惑。下面有三种情况：

In [2]:
# 1. 不拷贝：如果只是简单的赋值，那么不会进行拷贝。
a = np.arange(12)
b = a #这种情况不会进行拷贝
print(b is a) #返回True，说明b和a是相同的
print(id(a))
print(id(b))

True
140125955643712
140125955643712


In [3]:
# 2. View或者浅拷贝：有些情况，会进行变量的拷贝，但是他们所指向的内存空间都是一样的，那么这种情况叫做浅拷贝，或者叫做 View(视图)。
print(a)
c = a.view()
print(c)
print(c is a)
print(id(a))
print(id(c))

c[0] = 100
print(a)# ！！！！

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
False
140125955643712
140126335670432
[100   1   2   3   4   5   6   7   8   9  10  11]


In [4]:
# 3. 深拷贝：将之前数据完完整整的拷贝一份放到另外一块内存空间中，这样就是两个完全不同的值了。
print(a)
d = a.copy()
print(d is a)
print(id(a))
print(id(d))

d[0] = 1000
print(d)
print(a)# ！！！！

[100   1   2   3   4   5   6   7   8   9  10  11]
False
140125955643712
140125955644272
[1000    1    2    3    4    5    6    7    8    9   10   11]
[100   1   2   3   4   5   6   7   8   9  10  11]


In [5]:
# 像之前讲到的 flatten 和 ravel 就是这种情况， ravel 返回的就是View，而 flatten 返回的就是深拷贝。
a1 = np.random.randint(0,9, size=(2,4))
print(a1)
print("==" * 20)

a2 = a1.flatten()
a2[0] = 100
print(a2)
print(a1)# a1的值不变
print("==" * 20)

a3 = a1.ravel()
a3[0] = 100
print(a3)
print(a1)# a1的值也会被修改，即ravel()返回的是浅拷贝

[[0 7 5 4]
 [8 2 4 2]]
[100   7   5   4   8   2   4   2]
[[0 7 5 4]
 [8 2 4 2]]
[100   7   5   4   8   2   4   2]
[[100   7   5   4]
 [  8   2   4   2]]


# 文件操作
- 操作CSV文件：
- 文件保存：
    - 有时候我们有了一个数组，需要保存到文件中，那么可以使用 np.savetxt 来实现。
    - np.savetxt(frame, array, fmt='%.18e', delimiter=None)
        * frame : 文件、字符串或产生器，可以是.gz或.bz2的压缩文件
        * array : 存入文件的数组
        * fmt : 写入文件的格式，例如：%d %.2f %.18e
        * delimiter : 分割字符串，默认是任何空格

- 读取文件：
    - 有时候我们的数据是需要从文件中读取出来的，那么可以使用 np.loadtxt 来实现。
    - np.loadtxt(frame, dtype=np.float, delimiter=None, unpack=False)
        * frame：文件、字符串或产生器，可以是.gz或.bz2的压缩文件。
        * dtype：数据类型，可选。
        * delimiter：分割字符串，默认是任何空格。
        * skiprows：跳过前面x行。
        * usecols：读取指定的列，用元组组合。
        * unpack：如果True，读取出来的数组是转置后的。


In [6]:
scores = np.random.randint(0,101, size=(20,2))
print(scores)

[[ 73  75]
 [ 77  77]
 [ 88   9]
 [ 98  22]
 [ 78   1]
 [ 10  61]
 [ 80  88]
 [ 48  42]
 [ 56 100]
 [ 13  47]
 [  3  26]
 [ 27  58]
 [ 34  46]
 [ 32  90]
 [ 89  97]
 [ 84  66]
 [ 54  38]
 [ 22  22]
 [ 15  20]
 [ 31  33]]


In [7]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

In [8]:
# 文件保存
np.savetxt("score.csv", scores, fmt='%d', delimiter=",", header="数学,语文", comments="", encoding='utf-8')

In [9]:
# 文件读取
s = np.loadtxt("score.csv", dtype=np.int, delimiter=",", skiprows=1)
print(s)

[[ 73  75]
 [ 77  77]
 [ 88   9]
 [ 98  22]
 [ 78   1]
 [ 10  61]
 [ 80  88]
 [ 48  42]
 [ 56 100]
 [ 13  47]
 [  3  26]
 [ 27  58]
 [ 34  46]
 [ 32  90]
 [ 89  97]
 [ 84  66]
 [ 54  38]
 [ 22  22]
 [ 15  20]
 [ 31  33]]


## np独有的存储解决方案：

- numpy 中还有一种独有的存储解决方案。文件名是以 .npy 或者 npz 结尾的。
- 以下是存储和加载的函数: 
    - 存储： np.save(fname,array) 或 np.savez(fname,array) 。 
        - 其中，np.save函数的扩展名是 .npy ，np.savez的扩展名是 .npz ，np.savez是经过压缩的。 
    - 加载： np.load(fname) 。


In [10]:
c = np.random.randint(0,10, size=(2,3))
np.save('c', c)

In [11]:
c1 = np.load("c.npy")
print(c1)

[[6 6 7]
 [5 4 7]]


In [12]:
d = np.random.randint(0,10, size=(2,3,4))
#np.savetxt("d.csv", d)#只能保存一维或二维数组
np.save('d', d)

In [13]:
d1 = np.load('d.npy')
print(d1)

[[[1 1 4 0]
  [4 5 6 8]
  [2 6 3 1]]

 [[4 0 8 6]
  [7 0 0 7]
  [8 8 2 6]]]


# 总结：
1. 在数组操作中分成三种拷贝：
    - 不拷贝：直接赋值，栈区没有拷贝，只是用同一个栈区定义了不同的名称
    - 浅拷贝：只拷贝栈区，栈区指定的堆区并没有拷贝
    - 深拷贝：栈区和堆区都拷贝
 
2. np.savetxt 和 np.loadtxt 一般用来操作csv文件，他可以设置header，但是不能存储三维及以上的数组。
3. np.save 和 np.load 一般用来存储非文本类型的文件他不可以设置header，但是可以存储三维及以上的数组。
4. 如果想专门操作csv文件，还有另外一个模块，叫做 csv 。这个模块是python内置的，不需要安装，具体操作见 demo1.py 和 demo2.py 。

# 数组操作和文件操作作业
- 1.数组 a = np.random.rand(3,2,3) 能和 b = np.random.rand(3,2,2) 进行运算吗？能和 c = np.random.rand(3,1,1) 进行运算吗？请说明结果的原因。
- 2.将数组 a = np.random.rand(3,5) 和 b = np.random.rand(6,4) 叠加在一起，其中 a 在 b 的上面，并且在 b 的第2列（下标从0开始）新增一列，用0来填充。
- 3.将数组 a = np.random.rand(4,5) 扁平化成一维数组，可以使用 flatten 和 ravel ，对两者的返回值进行操作，哪个会影响到数组 a ？对会影响到 a 数组的那个函数，请说明详细的原因。
- 4.使用 numpy 自带的 csv 方法读取出 stock.csv 文件中 preClosePrice 、 openPrice 、 highestPrice 、 lowestPrice 的数据（提示：使用skiprows和usecols参数）。


In [14]:
# 1.数组 a = np.random.rand(3,2,3) 能和 b = np.random.rand(3,2,2) 进行运算吗？
#能和 c = np.random.rand(3,1,1) 进行运算吗？请说明结果的原因。
import numpy as np

a = np.random.rand(3,2,3)
b = np.random.rand(3,2,2)
c = np.random.rand(3,1,1)
#print(a+b)
print(a+c)
print("==" * 30)
print(b+c)
# 数组a和数组b不可以进行运算，数组a可以和数组c进行运算，b可以和c进行运算
# 造成以上结果的原因是因为数组的广播原则是看两个数组是否从末尾的维度开始判断其轴长度是否相等或其中一方等于一，才可以兼容
# a的末尾轴长度是3，b末尾轴长度是2，所以a，b不能兼容；c的末尾轴长度是1，中间也是1，开头和ab一样都是3，所以c可以和a或b兼容

[[[1.82165214 1.00797877 1.84306532]
  [1.79703213 1.54095988 1.74449744]]

 [[1.25411706 0.94228882 1.08219427]
  [1.21925723 1.30587864 0.91695459]]

 [[1.26784176 1.17395909 0.95125166]
  [1.23737155 1.27401662 1.60468262]]]
[[[1.74933711 1.44532104]
  [1.10841359 1.46184632]]

 [[1.0277814  0.40071867]
  [0.55713694 0.78996245]]

 [[1.25281133 1.3759566 ]
  [1.01581598 1.48555929]]]


In [1]:
# 2.将数组 a = np.random.rand(3,5) 和 b = np.random.rand(6,4) 叠加在一起，
#其中 a 在 b 的上面，并且在 b 的第2列（下标从0开始）新增一列，用0来填充。
import numpy as np

a = np.random.rand(3,5)
b = np.random.rand(6,4)
print(a)
print(b)
print("===" * 30)

c = np.zeros((6,1))
print(c)
print("===" * 30)

d, e = np.hsplit(b, (2))
print(d)
print(e)
print("===" * 30)

b = np.concatenate([d,c,e], axis=1)
print(b)
print("===" * 30)

print(np.vstack([a,b]))

[[0.95284084 0.99662209 0.83946054 0.82010866 0.78038917]
 [0.57241014 0.83854828 0.85825583 0.60870956 0.46851272]
 [0.23561506 0.33935846 0.01883475 0.86311306 0.15940519]]
[[0.19920373 0.76150368 0.89078536 0.43045442]
 [0.76548065 0.37811052 0.35018885 0.08649587]
 [0.65581803 0.64595364 0.53953577 0.59999645]
 [0.28441482 0.82757473 0.01293988 0.54921023]
 [0.16658497 0.84330437 0.60977565 0.20353096]
 [0.41407538 0.40329742 0.14783361 0.77297555]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.19920373 0.76150368]
 [0.76548065 0.37811052]
 [0.65581803 0.64595364]
 [0.28441482 0.82757473]
 [0.16658497 0.84330437]
 [0.41407538 0.40329742]]
[[0.89078536 0.43045442]
 [0.35018885 0.08649587]
 [0.53953577 0.59999645]
 [0.01293988 0.54921023]
 [0.60977565 0.20353096]
 [0.14783361 0.77297555]]
[[0.19920373 0.76150368 0.         0.89078536 0.43045442]
 [0.76548065 0.37811052 0.         0.35018885 0.08649587]
 [0.65581803 0.64595364 0.         0.53953577 0.59999645]
 [0.28441482 0.82757473 0.   

In [6]:
import numpy as np

a = np.random.rand(3,5)
b = np.random.rand(6,4)
print(a)
print(b)
print("===" * 30)

c = np.zeros((6,1))
print(c)
print("===" * 30)

b1 = np.concatenate([np.split(b, (2), axis=1)[0], c, np.split(b, (2), axis=1)[1]], axis=1)
print(np.concatenate([a, b1], axis=0))

[[0.40248246 0.35115024 0.75494279 0.67160567 0.83864343]
 [0.64476056 0.03683723 0.7474422  0.55977842 0.65910561]
 [0.43011774 0.63657567 0.44365207 0.40133047 0.26929094]]
[[0.21592715 0.85472262 0.25772336 0.37882321]
 [0.08185163 0.8010165  0.124544   0.987457  ]
 [0.52817204 0.71788807 0.35939328 0.40315778]
 [0.46518303 0.5327747  0.48785257 0.62833535]
 [0.75348121 0.88774844 0.40405104 0.452608  ]
 [0.21342115 0.94260633 0.2265115  0.76653215]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.40248246 0.35115024 0.75494279 0.67160567 0.83864343]
 [0.64476056 0.03683723 0.7474422  0.55977842 0.65910561]
 [0.43011774 0.63657567 0.44365207 0.40133047 0.26929094]
 [0.21592715 0.85472262 0.         0.25772336 0.37882321]
 [0.08185163 0.8010165  0.         0.124544   0.987457  ]
 [0.52817204 0.71788807 0.         0.35939328 0.40315778]
 [0.46518303 0.5327747  0.         0.48785257 0.62833535]
 [0.75348121 0.88774844 0.         0.40405104 0.452608  ]
 [0.21342115 0.94260633 0.         0.2265

In [16]:
# 3.将数组 a = np.random.rand(4,5) 扁平化成一维数组，可以使用 flatten 和 ravel ，对两者的返回值进行操作，
#哪个会影响到数组 a ？对会影响到 a 数组的那个函数，请说明详细的原因。
import numpy as np

a = np.random.rand(4,5)
print(a)
print("===" * 30)

af = a.flatten()
af[0:5] = 0
print(a)
print("===" * 30)

ar = a.ravel()
ar[0:5] = 0
print(a)
# 以上结果是flatten()没有影响到原数组，而ravel() 对原数组的返回值产生影响。
# 原因是flatten()是深拷贝，堆区和栈区全都拷贝了；
# 而ravel()是浅拷贝，只拷贝栈区的变量，对其指向的堆区的数组并没有拷贝，还是指向同一个数组

[[0.2508824  0.48331044 0.82423252 0.67807685 0.28037583]
 [0.04364535 0.53478606 0.90376374 0.73836993 0.30317894]
 [0.61546819 0.7448427  0.94253157 0.49535867 0.39408998]
 [0.49604084 0.98392509 0.21616166 0.74809193 0.31863358]]
[[0.2508824  0.48331044 0.82423252 0.67807685 0.28037583]
 [0.04364535 0.53478606 0.90376374 0.73836993 0.30317894]
 [0.61546819 0.7448427  0.94253157 0.49535867 0.39408998]
 [0.49604084 0.98392509 0.21616166 0.74809193 0.31863358]]
[[0.         0.         0.         0.         0.        ]
 [0.04364535 0.53478606 0.90376374 0.73836993 0.30317894]
 [0.61546819 0.7448427  0.94253157 0.49535867 0.39408998]
 [0.49604084 0.98392509 0.21616166 0.74809193 0.31863358]]


In [17]:
# 4.1 使用 numpy 自带的 csv 方法读取出 stock.csv 文件中 
#preClosePrice 、 openPrice 、 highestPrice 、 lowestPrice 的数据（提示：使用skiprows和usecols参数）。
import numpy as np
import csv

with open('stock.csv', 'r', encoding='utf-8') as fp:
    reader = csv.reader(fp)
    next(reader)
    for r in reader:
        preClosePrice = r[6]
        openPrice = r[7]
        highestPrice = r[8]
        lowestPrice = r[9]
        print({'preClosePrice':preClosePrice, 'openPrice':openPrice, 
               'highestPrice':highestPrice, 'lowestPrice':lowestPrice})
    

{'preClosePrice': '13.38', 'openPrice': '13.4', 'highestPrice': '13.48', 'lowestPrice': '12.96'}
{'preClosePrice': '31.22', 'openPrice': '30.5', 'highestPrice': '32.03', 'lowestPrice': '30.5'}
{'preClosePrice': '25.56', 'openPrice': '25.41', 'highestPrice': '26.4', 'lowestPrice': '25.18'}
{'preClosePrice': '4.2', 'openPrice': '4.2', 'highestPrice': '4.24', 'lowestPrice': '4.2'}
{'preClosePrice': '9.85', 'openPrice': '0', 'highestPrice': '0', 'lowestPrice': '0'}
{'preClosePrice': '16.66', 'openPrice': '0', 'highestPrice': '0', 'lowestPrice': '0'}
{'preClosePrice': '8.48', 'openPrice': '8.48', 'highestPrice': '8.74', 'lowestPrice': '8.41'}
{'preClosePrice': '7.6', 'openPrice': '7.61', 'highestPrice': '7.63', 'lowestPrice': '7.53'}
{'preClosePrice': '5.13', 'openPrice': '5.13', 'highestPrice': '5.23', 'lowestPrice': '5.11'}
{'preClosePrice': '17.18', 'openPrice': '17.08', 'highestPrice': '17.28', 'lowestPrice': '17'}
{'preClosePrice': '9.19', 'openPrice': '9.1', 'highestPrice': '9.28', 'l

{'preClosePrice': '10.4', 'openPrice': '10.23', 'highestPrice': '10.67', 'lowestPrice': '9.94'}
{'preClosePrice': '24.93', 'openPrice': '0', 'highestPrice': '0', 'lowestPrice': '0'}
{'preClosePrice': '19.6', 'openPrice': '0', 'highestPrice': '0', 'lowestPrice': '0'}
{'preClosePrice': '9.49', 'openPrice': '9.42', 'highestPrice': '9.52', 'lowestPrice': '9.36'}
{'preClosePrice': '7.85', 'openPrice': '7.87', 'highestPrice': '7.94', 'lowestPrice': '7.73'}
{'preClosePrice': '10.08', 'openPrice': '0', 'highestPrice': '0', 'lowestPrice': '0'}
{'preClosePrice': '6.12', 'openPrice': '0', 'highestPrice': '0', 'lowestPrice': '0'}
{'preClosePrice': '7.98', 'openPrice': '7.97', 'highestPrice': '8.09', 'lowestPrice': '7.93'}
{'preClosePrice': '5.27', 'openPrice': '0', 'highestPrice': '0', 'lowestPrice': '0'}
{'preClosePrice': '61.78', 'openPrice': '61.95', 'highestPrice': '62.9', 'lowestPrice': '61.84'}
{'preClosePrice': '6.59', 'openPrice': '6.55', 'highestPrice': '6.65', 'lowestPrice': '6.53'}
{'pr

In [18]:
# 4.2 使用 numpy 自带的 csv 方法读取出 stock.csv 文件中 
#preClosePrice 、 openPrice 、 highestPrice 、 lowestPrice 的数据（提示：使用skiprows和usecols参数）。
import numpy as np
import csv

with open('stock.csv', 'r', encoding='utf-8') as fp:
    reader = csv.DictReader(fp)
    for r in reader:
        print({'preClosePrice':r["preClosePrice"], 'openPrice':r["openPrice"],
              'highestPrice':r["highestPrice"], 'lowestPrice':r["lowestPrice"]})
        

{'preClosePrice': '13.38', 'openPrice': '13.4', 'highestPrice': '13.48', 'lowestPrice': '12.96'}
{'preClosePrice': '31.22', 'openPrice': '30.5', 'highestPrice': '32.03', 'lowestPrice': '30.5'}
{'preClosePrice': '25.56', 'openPrice': '25.41', 'highestPrice': '26.4', 'lowestPrice': '25.18'}
{'preClosePrice': '4.2', 'openPrice': '4.2', 'highestPrice': '4.24', 'lowestPrice': '4.2'}
{'preClosePrice': '9.85', 'openPrice': '0', 'highestPrice': '0', 'lowestPrice': '0'}
{'preClosePrice': '16.66', 'openPrice': '0', 'highestPrice': '0', 'lowestPrice': '0'}
{'preClosePrice': '8.48', 'openPrice': '8.48', 'highestPrice': '8.74', 'lowestPrice': '8.41'}
{'preClosePrice': '7.6', 'openPrice': '7.61', 'highestPrice': '7.63', 'lowestPrice': '7.53'}
{'preClosePrice': '5.13', 'openPrice': '5.13', 'highestPrice': '5.23', 'lowestPrice': '5.11'}
{'preClosePrice': '17.18', 'openPrice': '17.08', 'highestPrice': '17.28', 'lowestPrice': '17'}
{'preClosePrice': '9.19', 'openPrice': '9.1', 'highestPrice': '9.28', 'l

{'preClosePrice': '16.92', 'openPrice': '16.86', 'highestPrice': '16.98', 'lowestPrice': '16.73'}
{'preClosePrice': '25.44', 'openPrice': '25.29', 'highestPrice': '25.7', 'lowestPrice': '25.06'}
{'preClosePrice': '10.65', 'openPrice': '10.62', 'highestPrice': '10.73', 'lowestPrice': '10.45'}
{'preClosePrice': '14.4', 'openPrice': '14.4', 'highestPrice': '15.05', 'lowestPrice': '14.37'}
{'preClosePrice': '5.26', 'openPrice': '0', 'highestPrice': '0', 'lowestPrice': '0'}
{'preClosePrice': '19', 'openPrice': '19', 'highestPrice': '19.19', 'lowestPrice': '18.58'}
{'preClosePrice': '6.47', 'openPrice': '6.45', 'highestPrice': '6.45', 'lowestPrice': '6.4'}
{'preClosePrice': '4.88', 'openPrice': '4.99', 'highestPrice': '4.99', 'lowestPrice': '4.82'}
{'preClosePrice': '14.15', 'openPrice': '14.09', 'highestPrice': '14.25', 'lowestPrice': '13.97'}
{'preClosePrice': '6.2', 'openPrice': '6.19', 'highestPrice': '6.27', 'lowestPrice': '6.16'}
{'preClosePrice': '5.75', 'openPrice': '0', 'highestPric

In [19]:
# 4.3 
# encoding:utf-8
import numpy as np


dp = np.loadtxt('stock.csv', dtype=np.float, delimiter=',', skiprows=1, usecols=[6,7,8,9])
print(dp)

[[13.38 13.4  13.48 12.96]
 [31.22 30.5  32.03 30.5 ]
 [25.56 25.41 26.4  25.18]
 ...
 [14.03 13.99 14.26 13.85]
 [ 7.97  7.92  8.04  7.88]
 [23.37 23.49 23.    7.88]]


In [20]:
help(np.loadtxt)

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
  