# Numpy数组操作

## 数组广播机制：
- 数组与数的计算：
- 在 Python 列表中，想要对列表中所有的元素都加一个数，要么采用 map 函数，要么循环整个列表进行操作。但是 NumPy 中的数组可以直接在数组上进行操作


In [1]:
import numpy as np

In [2]:
a1 = np.random.randint(0,10, size=(3,4))
print(a1)

[[0 1 1 3]
 [4 4 6 5]
 [9 6 6 7]]


In [3]:
print(a1*10)

[[ 0 10 10 30]
 [40 40 60 50]
 [90 60 60 70]]


In [4]:
print(a1-10)

[[-10  -9  -9  -7]
 [ -6  -6  -4  -5]
 [ -1  -4  -4  -3]]


In [5]:
print(a1+10)

[[10 11 11 13]
 [14 14 16 15]
 [19 16 16 17]]


In [6]:
print(a1/10)

[[ 0.   0.1  0.1  0.3]
 [ 0.4  0.4  0.6  0.5]
 [ 0.9  0.6  0.6  0.7]]


In [7]:
a2 = np.random.randint(0,10, size=(3,4))
print(a2)

[[2 4 0 0]
 [4 0 5 0]
 [8 1 3 1]]


In [8]:
# 1. 结构相同的数组与数组之间的运算
print(a1 + a2)

[[ 2  5  1  3]
 [ 8  4 11  5]
 [17  7  9  8]]


In [9]:
# 2. 结构不相同的数组之间的运算（会报错！！！）
a3 = np.random.randint(0,10, size=(4,4))
print(a3)
#print(a2+a3)# ！！！！！！！！

[[3 7 0 3]
 [3 4 2 0]
 [6 8 0 1]
 [1 6 8 8]]


In [10]:
# 3. 与行数相同并且只有1列的数组之间的运算
a4 = np.random.randint(0,10, size=(3,1))
print(a1)
print("=="*20)

print(a4)
print("=="*20)

print(a1+a4)

[[0 1 1 3]
 [4 4 6 5]
 [9 6 6 7]]
[[9]
 [8]
 [7]]
[[ 9 10 10 12]
 [12 12 14 13]
 [16 13 13 14]]


In [11]:
# 4.与列数相同并且只有1行的数组之间的运算 
a5 = np.random.randint(0,10, size=(1,4))
print(a1)
print("=="*20)

print(a5)
print("=="*20)

print(a1+a5)

[[0 1 1 3]
 [4 4 6 5]
 [9 6 6 7]]
[[4 1 2 6]]
[[ 4  2  3  9]
 [ 8  5  8 11]
 [13  7  8 13]]


## 广播原则！！！！！！
- 如果两个数组的后缘维度（trailing dimension，即从末尾开始算起的维度）的轴长度相符或其中一方的长度为1，则认为他们是广播兼容的。
- 广播会在缺失和（或）长度为1的维度上进行，看一下例子分析
- shape 为 (3,8,2) 的数组能和 (8,3) 的数组进行运算吗？
    - 分析：不能，因为按照广播原则，从后面往前面数， (3,8,2) 和 (8,3) 中的 2 和 3 不相等，所以不能进行运算。
- shape 为 (3,8,2) 的数组能和 (8,1) 的数组进行运算吗？
    - 分析：能，因为按照广播原则，从后面往前面数， (3,8,2) 和 (8,1) 中的 2 和 1 虽然不相等，但是因为有一方的长度为 1 ，所以能参与运算。
- shape 为 (3,1,4) 的数组能和 (8,1) 的数组进行运算吗？
    - 分析：能，因为按照广播原则，从后面往前面数， (3,1,4) 和 (8,1) 中的 4 和 1 虽然不相等且 1 和 8 不相等，但是因为这两项中有一方的长度为 1 ，所以能参与运算。

In [12]:
a6 = np.random.randint(0,10, size=(3,8,2))
a7 = np.random.randint(0,10, size=(8,3))
#print(a6+a7) # 会出错

In [13]:
a6 = np.random.randint(0,10, size=(3,8,2))
a7 = np.random.randint(0,10, size=(8,1))
print(a6+a7)

[[[10  5]
  [18 11]
  [ 6  7]
  [17 14]
  [10 11]
  [ 6 13]
  [ 4  4]
  [13  9]]

 [[ 6  1]
  [13 13]
  [ 2  4]
  [13 12]
  [ 7  4]
  [11 13]
  [ 7  6]
  [12 18]]

 [[ 6  1]
  [18 18]
  [ 1  2]
  [12 15]
  [ 6  4]
  [11  9]
  [ 8  1]
  [ 9 14]]]


In [14]:
a6 = np.random.randint(0,10, size=(3,1,4))
a7 = np.random.randint(0,10, size=(8,1))
print(a6)
print("==" * 20)
print(a7)
print("==" * 20)
print(a6+a7)

[[[4 8 2 6]]

 [[0 7 3 7]]

 [[9 5 5 9]]]
[[0]
 [1]
 [1]
 [9]
 [3]
 [5]
 [1]
 [2]]
[[[ 4  8  2  6]
  [ 5  9  3  7]
  [ 5  9  3  7]
  [13 17 11 15]
  [ 7 11  5  9]
  [ 9 13  7 11]
  [ 5  9  3  7]
  [ 6 10  4  8]]

 [[ 0  7  3  7]
  [ 1  8  4  8]
  [ 1  8  4  8]
  [ 9 16 12 16]
  [ 3 10  6 10]
  [ 5 12  8 12]
  [ 1  8  4  8]
  [ 2  9  5  9]]

 [[ 9  5  5  9]
  [10  6  6 10]
  [10  6  6 10]
  [18 14 14 18]
  [12  8  8 12]
  [14 10 10 14]
  [10  6  6 10]
  [11  7  7 11]]]


## 数组形状的操作：
- 可以通过一些函数，非常方便的操作数组的形状。
- reshape和resize方法：两个方法都是用来修改数组形状的，但是有一些不同。
    1. reshape 是将数组转换成指定的形状，然后返回转换后的结果，对于原数组的形状是不会发生改变的。
    2. resize 是将数组转换成指定的形状，会直接修改数组本身。并不会返回任何值。

In [15]:
a1 = np.random.randint(0,10, size=(3,4))
print(a1)

[[3 1 5 8]
 [5 5 9 3]
 [4 2 6 5]]


In [16]:
print(a1.reshape((2,6)))
print(a1)

[[3 1 5 8 5 5]
 [9 3 4 2 6 5]]
[[3 1 5 8]
 [5 5 9 3]
 [4 2 6 5]]


In [17]:
print(a1.resize((2,6)))
print(a1)

None
[[3 1 5 8 5 5]
 [9 3 4 2 6 5]]


## flatten和ravel方法：
- 两个方法都是将多维数组转换为一维数组，但是有以下不同： 
    1. flatten 是将数组转换为一维数组后，然后将这个拷贝返回回去，所以后续对这个返回值进行修改不会影响之前的数组。 
    2. ravel 是将数组转换为一维数组后，将这个视图（可以理解为引用）返回回去，所以后续对这个返回值进行修改会影响之前的数组。

In [18]:
a2 = np.random.randint(0,10, size=(3,4))
print(a2)

[[2 4 7 3]
 [0 1 7 8]
 [3 9 2 1]]


In [19]:
print(a2.flatten())
print(a2)# 不影响原数组的结构形状

[2 4 7 3 0 1 7 8 3 9 2 1]
[[2 4 7 3]
 [0 1 7 8]
 [3 9 2 1]]


In [20]:
print(a2.ravel())
print(a2)# 同样不影响原数组的结构形状

[2 4 7 3 0 1 7 8 3 9 2 1]
[[2 4 7 3]
 [0 1 7 8]
 [3 9 2 1]]


In [21]:
a3 = a2.flatten()
a3[0] = 100
print(a3)
print(a2)# 当修改a3的元素时，a2中的元素不会发生更改

[100   4   7   3   0   1   7   8   3   9   2   1]
[[2 4 7 3]
 [0 1 7 8]
 [3 9 2 1]]


In [22]:
a4 = a2.ravel()
a4[0] = 100
print(a3)
print(a2)# 当修改a3的元素时，a2中的元素会随之改变

[100   4   7   3   0   1   7   8   3   9   2   1]
[[100   4   7   3]
 [  0   1   7   8]
 [  3   9   2   1]]


## 不同数组的组合
- 如果有多个数组想要组合在一起，也可以通过其中的一些函数来实现。

In [23]:
#  vstack ：将数组按垂直方向进行叠加。
vs1 = np.random.randint(0,10, size=(3,4))
print(vs1)

[[3 6 2 8]
 [0 5 8 9]
 [2 0 8 6]]


In [24]:
vs2 = np.random.randint(0,10, size=(2,4))
print(vs2)

[[3 5 7 0]
 [8 7 1 4]]


In [25]:
vs3 = np.vstack([vs1, vs2])
print(vs3)

[[3 6 2 8]
 [0 5 8 9]
 [2 0 8 6]
 [3 5 7 0]
 [8 7 1 4]]


In [26]:
#  hstack ：将数组按水平方向进行叠加。
hs1 = np.random.randint(0,10, size=(3,4))
print(hs1)

[[4 7 2 1]
 [6 8 9 2]
 [0 0 8 7]]


In [27]:
hs2 = np.random.randint(0,10, size=(3,2))
print(hs2)

[[1 6]
 [7 0]
 [4 5]]


In [28]:
hs3 = np.hstack([hs2, hs1])
print(hs3)

[[1 6 4 7 2 1]
 [7 0 6 8 9 2]
 [4 5 0 0 8 7]]


In [29]:
# concatenate([],axis) ：将两个数组进行叠加，但是具体是按水平方向还是按垂直方向。则要看 axis 的参数；
# 如果 axis=0 ，那么代表的是往垂直方向（行）叠加，
# 如果 axis=1 ，那么代表的是往水平方向（列）上叠加，
# 如果 axis=None ，那么会将两个数组组合成一个一维数组。
# 需要注意的是，如果往水平方向上叠加，那么行必须相同，如果是往垂直方向叠加，那么列必须相同
c1 = np.concatenate([vs1, vs2], axis=0)
print(c1)
print("=" * 20)
c2 = np.concatenate([hs2, hs1], axis=1)
print(c2)
print("==" * 20)
c3 = np.concatenate([vs1, vs2], axis=None)
print(c3)

[[3 6 2 8]
 [0 5 8 9]
 [2 0 8 6]
 [3 5 7 0]
 [8 7 1 4]]
[[1 6 4 7 2 1]
 [7 0 6 8 9 2]
 [4 5 0 0 8 7]]
[3 6 2 8 0 5 8 9 2 0 8 6 3 5 7 0 8 7 1 4]


## 数组的切割：
- 通过 hsplit 和 vsplit 以及 array_split 可以将一个数组进行切割。

In [30]:
# hsplit ：按照水平方向进行切割。
# 用于指定分割成几列，可以使用数字来代表分成几部分，也可以使用数组来代表分割的地方
hs1 = np.random.randint(0,10, size=(4,6))
print(hs1)

[[0 6 9 3 4 2]
 [1 6 7 5 6 3]
 [7 1 5 2 0 7]
 [1 7 8 2 8 6]]


In [31]:
print(np.hsplit(hs1, 2))# 均分n段切割

[array([[0, 6, 9],
       [1, 6, 7],
       [7, 1, 5],
       [1, 7, 8]]), array([[3, 4, 2],
       [5, 6, 3],
       [2, 0, 7],
       [2, 8, 6]])]


In [32]:
print(np.hsplit(hs1, (1,2,3,5)))# 元组里顺序切割，想切几段就切几段

[array([[0],
       [1],
       [7],
       [1]]), array([[6],
       [6],
       [1],
       [7]]), array([[9],
       [7],
       [5],
       [8]]), array([[3, 4],
       [5, 6],
       [2, 0],
       [2, 8]]), array([[2],
       [3],
       [7],
       [6]])]


In [33]:
# vsplit ：按照垂直方向进行切割。
# 用于指定分割成几行，可以使用数字来代表分成几部分，也可以使用数组来代表分割的地方
vs1 = np.random.randint(0,10, size=(4,5))
print(vs1)

[[6 6 7 3 7]
 [9 9 0 3 3]
 [1 7 9 8 9]
 [3 7 8 2 9]]


In [34]:
print(np.vsplit(vs1, 4))# 均分四段切割

[array([[6, 6, 7, 3, 7]]), array([[9, 9, 0, 3, 3]]), array([[1, 7, 9, 8, 9]]), array([[3, 7, 8, 2, 9]])]


In [35]:
print(np.vsplit(vs1, (1,3)))# 随意切割

[array([[6, 6, 7, 3, 7]]), array([[9, 9, 0, 3, 3],
       [1, 7, 9, 8, 9]]), array([[3, 7, 8, 2, 9]])]


In [36]:
# split/array_split(array,indicate_or_seciont,axis) ：
# 用于指定切割方式，在切割的时候需要指定是沿着水平方向还是垂直方向；
# axis=1 代表沿着水平方向切割，
# axis=0 代表沿着垂直方向切割
print(hs1)
print(vs1)
print(np.split(hs1, 6, axis=1))

[[0 6 9 3 4 2]
 [1 6 7 5 6 3]
 [7 1 5 2 0 7]
 [1 7 8 2 8 6]]
[[6 6 7 3 7]
 [9 9 0 3 3]
 [1 7 9 8 9]
 [3 7 8 2 9]]
[array([[0],
       [1],
       [7],
       [1]]), array([[6],
       [6],
       [1],
       [7]]), array([[9],
       [7],
       [5],
       [8]]), array([[3],
       [5],
       [2],
       [2]]), array([[4],
       [6],
       [0],
       [8]]), array([[2],
       [3],
       [7],
       [6]])]


In [37]:
print(np.split(vs1,5, axis=1))

[array([[6],
       [9],
       [1],
       [3]]), array([[6],
       [9],
       [7],
       [7]]), array([[7],
       [0],
       [9],
       [8]]), array([[3],
       [3],
       [8],
       [2]]), array([[7],
       [3],
       [9],
       [9]])]


## 数组（矩阵）转置和轴对换：
- numpy 中的数组其实就是线性代数中的矩阵。矩阵是可以进行转置的。 
- ndarray 有一个 T 属性，可以返回这个数组的转置的结果。

In [38]:
t1 = np.random.randint(0,10, size=(4,5))
print(t1)

[[7 3 2 8 0]
 [2 4 6 6 8]
 [4 5 4 4 2]
 [8 3 2 3 0]]


In [39]:
# 矩阵转置方法1: T 不会修改原数组
t2 = t1.T
print(t2)
print(t1)

[[7 2 4 8]
 [3 4 5 3]
 [2 6 4 2]
 [8 6 4 3]
 [0 8 2 0]]
[[7 3 2 8 0]
 [2 4 6 6 8]
 [4 5 4 4 2]
 [8 3 2 3 0]]


In [40]:
# ndarray.dot() 线性代数中的矩阵的内积算法！！！
print(t1.dot(t1.T))

[[126  86  83  93]
 [ 86 156  92  58]
 [ 83  92  77  67]
 [ 93  58  67  86]]


In [41]:
# 矩阵转置方法2: transpose() 不会修改原数组，但是对transpose()的返回值进行修改会影响到原数组
t3 = t1.transpose()
t3[0] = 11
print(t3)
print(t1)

[[11 11 11 11]
 [ 3  4  5  3]
 [ 2  6  4  2]
 [ 8  6  4  3]
 [ 0  8  2  0]]
[[11  3  2  8  0]
 [11  4  6  6  8]
 [11  5  4  4  2]
 [11  3  2  3  0]]


In [42]:
print(t1.dot(t1.transpose()))

[[198 193 176 158]
 [193 273 205 163]
 [176 205 182 156]
 [158 163 156 143]]


# 总结：
1. 数组和数字直接进行运算是没有问题的
2. 两个shape相同的数组是可以进行运算的
3. 如果两个shape不同的数组想要进行计算，需要遵广播原则：
    - 如果两个数组的后缘维度（trailing dimension，即从末尾开始算起的维度）的轴长度相符或其中一方的长度为1，则认为他们是广播兼容的。广播会在缺失和（或）长度为1的维度上进行。
    
4. reshape 和 resize 都是重新定义形状的，但是，reshape不会修改数组本身，而是将修改后的结果直接返回回去，而resize则是直接修改数组本身的。
5. flatten 和 ravel 都是用来将多维数组转换成一维数组的，并且他们都不会对原数组的形状进行修改，但是flatten返回的是一个拷贝，所以对flatten的返回值的修改不会影响到原数组的值，而ravel返回的是一个View，所以对它返回值的修改会影响到原数组的值。

6. hstack 代表在水平方向叠加，如果想要叠加成功，那么他们的行必须一致。
7. vstack 代表在垂直方向叠加，如果想要叠加成功，那么他们的列必须一致。
8. concatenate 可以手动的指定axis的参数，如果axis=0，代表往垂直方向(行)叠加，如果axis=1，代表往水平方向(列)叠加，如果axis=None，代表会先进行叠加，再转换成一维数组。

9. hsplit 代表往水平方向（列）切割，它的切割方式有两种：第一种是平均分开进行切割，第二种是指定下标值（元组的形式）进行切割。
10. vsplit 代表在垂直方向（行）切割，它的切割方式同hsplit一致。
11. split/array_split 是手动的指定axis参数axis=0，代表沿垂直方向（行）进行切割，axis=1，代表沿水平方向（列）进行切割。

12. 可以通过 ndarray.T 的形式进行转置
13. 也可以通过 ndarray.transpose() 的进行转置，此方法返回的是一个View，所以若果对返回值进行修改，会影响到原来的数组。