In [1]:
import numpy as np

In [2]:
#  ndarray.ndim 判断数组的维数
a1 = np.array([1,2,3])
print(a1.ndim)
a2 = np.array([[1,2,3], [4,5,6]])
print(a2.ndim)
a3 = np.array([
    [
        [1,2,3], 
        [4,5,6]
    ],
    [
        [11,12,13],
        [14,15,16]
    ]
])
print(a3.ndim)

1
2
3


In [3]:
# ndarray.shape 写出数组的形状？
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(2, 2, 3)


In [4]:
# ndarray.reshape 修改数组的维数
a4 = a3.reshape((2, 6))# 注意修改后的元素个数与修改前的要一致
print(a4)
print(a4.shape)

print(a3)# 不会修改原数组！！！
a3.reshape((2, 6))# 不会修改原数组！！！
print(a3)

[[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]]
(2, 6)
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [5]:
# ndarray.resize 修改数组的维数, 可以直接修改原数组
a5 = np.array([
    [
        [1,2,3], 
        [4,5,6]
    ],
    [
        [11,12,13],
        [14,15,16]
    ]
])
print(a5)
a5.resize(2,6)
print(a5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
[[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]]


In [6]:
# 注意以下数组维数的修改
a1 = np.arange(1,13)
print(a1)
print(a1.ndim)

a2 = a1.reshape(3,2,2)# 分3大段，每段为2行2列
print(a2)
print(a2.ndim)

a3 = a2.reshape(1,12)# 注意这里是二维数组，1行12列
print(a3)
print(a3.ndim)

a4 = a2.reshape(12,)# 这才是一维数组的改法
print(a4)
print(a4.ndim)

# adarray.flatten 将数组维数改变成一维(扁平化)
a5 = a2.flatten()# 不管a2是几维数组，都将他变成一个一维数组
print(a5)
print(a5.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
2
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [7]:
# ndarray.size: 获取数组中总的元素的个数
a1 = np.arange(1,13)
count1 = a1.size
print(count1)

a2 = a1.reshape(2,2,3)
count2 = a2.size
print(count2)

12
12


In [8]:
#  ndarray.itemsize: 数组中每个元素占的大小，单位是字节(一个字节是8位)
a1 = np.arange(1,13)
print(a1.itemsize)# 输出为8，说明1个元素占了8个字节，一个字节是8位，则为8*8=64位,即数据类型是64位的类型
print(a1.dtype)
# 计算数组中的所有元素所占的字节数量
print(a1.itemsize*a1.size)# 数组中的元素个数乘以每个元素所占的字节数量

8
int64
96


In [9]:
# Numpy索引和切片操作
import numpy as np

In [10]:
# 1. 一维数组的索引和切片操作(与python中的list相似)
a1 = np.arange(10)
#1.1 索引
print(a1[0])
# 1.2 切片
print(a1[4:6])
# 1.3 使用步长
print(a1[::2])
# 1.4 使用负数作为索引
print(a1[-1:-11:-2])

0
[4 5]
[0 2 4 6 8]
[9 7 5 3 1]


In [11]:
# 2. 多维数组
# 也是通过中括号来索引和切片，在中括号中，使用逗号进行分隔，逗号前面的是行，逗号后面的是列
# 如果多维数组中只有一个值，那么这个值就是行
a2 = np.random.randint(0,10, size=(4,6))
print(a2)

[[6 2 0 0 9 0]
 [6 5 4 7 9 2]
 [2 4 6 8 4 0]
 [9 0 9 0 8 9]]


In [12]:
print(a2[0])
print("==" * 30)

print(a2[1:3])# 注意索引是从零开始，左包括右不包括
print("==" * 30)

print(a2[1, 3])
print("==" * 30)

print(a2[[0,2,3]])# 只要第0,2,3行，不要第1行，即不连续的切片
print("==" * 30)

print(a2[[1,2],[4,5]])# 第1行第四列，第2行第5列，不连续的两个数据
print("==" * 30)

print(a2[1:3, 4:6])# 第1,2行的4,5列，连续的四个数（还是左包括右不包括）
print("==" * 30)

print(a2[:, 2])# 只要第2列
print("==" * 30)

print(a2[:, 2:4])# 第2-3列
print("==" * 30)

[6 2 0 0 9 0]
[[6 5 4 7 9 2]
 [2 4 6 8 4 0]]
7
[[6 2 0 0 9 0]
 [2 4 6 8 4 0]
 [9 0 9 0 8 9]]
[9 0]
[[9 2]
 [4 0]]
[0 4 6 9]
[[0 0]
 [4 7]
 [6 8]
 [9 0]]


In [13]:
# 布尔索引：布尔运算也是矢量的
a2 = np.arange(24).reshape(4,6)
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [14]:
print(a2 < 10)

[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]


In [15]:
print(a2[a2 < 10])

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# 其中布尔运算可以有 != 、 == 、 > 、 < 、 >= 、 <= 以及 &(与) 和 |(或) 
# | 和 &
print(a2[(a2 < 5) | (a2 > 10)])# 注意条件要用小括号括起来
print(a2[(a2 > 5) & (a2 < 10)])

[ 0  1  2  3  4 11 12 13 14 15 16 17 18 19 20 21 22 23]
[6 7 8 9]


In [17]:
# 值的替换：利用索引，也可以做一些值的替换。把满足条件的位置的值替换成其他的值
a3 = np.random.randint(0,10, size=(3,4))
print(a3)
a3[1] = 0# 利用索引替换元素值
print(a3)

[[5 4 8 6]
 [9 3 0 5]
 [1 0 7 6]]
[[5 4 8 6]
 [0 0 0 0]
 [1 0 7 6]]


In [18]:
a3[1] = np.array([2,3,4,5])# 注意元素的数量一致
print(a3)

[[5 4 8 6]
 [2 3 4 5]
 [1 0 7 6]]


In [19]:
# 也可以使用条件索引来实现
a3[a3 < 3] = 1
print(a3)

[[5 4 8 6]
 [1 3 4 5]
 [1 1 7 6]]


In [20]:
# 还可以使用函数来实现
# where函数
result = np.where(a3 < 5)# 单纯判断小于5的在第几行第几列
print(result)

(array([0, 1, 1, 1, 2, 2]), array([1, 0, 1, 2, 0, 1]))


In [21]:
result = np.where(a3 < 5, 0, 1)# 将全部小于5的替换成0，大于等于5的替换成1！！！
print(result)

[[1 0 1 1]
 [0 0 0 1]
 [0 0 1 1]]


# 总结
1. 数组一般达到3维就非常复杂了，不方便计算，所以一般会把3维以上的数组转化为2维数组来进行计算
2. 通过ndarray.ndim可以看到数组的维度
3. 通过ndarray.shape可以看到数组的形状（几行几列）shape是一个元组，里面有几个元素就代表是几维的数组
4. 通过ndarray.reshape可以改变数组的形状及维度，修改形状后数组的元素个数必须和原数组的元素个数一致，不会修改原数组的形状，只会将结果返回
5. 通过ndarray.size可以看到数组里元素的总数量
6. 通过ndarray.itemsize可以看到数组中每个元素所占内存的大小，单位是字节

7. 如果数组是一维的，那么数组的索引和切片是与python中的list是一样的
8. 如果是数组是多维的（以二维为例子），那么在中括号中给用逗号分隔开的两个值，其中逗号前面的表示行，后面的表示列，如果只有一个值（没有逗号的前提下），则只代表行！
9. 在行的单独部分和列的单独部分中的索引和切片操作遵循一维数组的操作，需注意可以用中括号的形式来操作不连续的行或者列
 
10. 布尔索引是通过相同数组上的True还是False来进行提取的。提取的条件可以有多个，如果有多个条件，每个条件要用小括号括起来，条件与条件之间用|（or）或者 &（and）连接

11. 可以使用索引或者切片来替换数组的元素
12. 可以使用条件索引来替换数组的元素
13. 可以使用where函数来实现替换数组的元素

# Numpy索引和切片作业！！！！！！

1. 将 np.arange(10) 数组中的奇数全部都替换成 -1 。
2. 有一个 4 行 4 列的数组（比如： np.random.randint(0,10,size=(4,4)) ），请将其中对角线的数取出来形成一个一维数组。提示（使用 np.eye ）。
3. 有一个 4 行 4 列的数组，请取出其中 (0,0),(1,2),(3,2) 的点。
4. 有一个 4 行 4 列的数组，请取出其中 2-3 行（包括第3行）的所有数据。(第0行开始算起！！！)
5. 有一个 8 行 9 列的数组，请将其中1-5行（包含第5行）的第8列大于3的数全部都取出来。(第0行开始算起！！！)


In [22]:
# 1
import numpy as np
a1 = np.arange(10)
a1[a1 %2 != 0] = -1
print(a1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [23]:
# 2
import numpy as np
a2 = np.random.randint(0,10,size=(4,4))
print(a2)
print(a2[[0,1,2,3], [0,1,2,3]])

[[7 4 3 8]
 [0 0 0 4]
 [0 0 5 0]
 [5 9 9 0]]
[7 0 5 0]


In [24]:
# 2 原答案
eye = np.eye(4, dtype=bool)
print(a2[eye])

[7 0 5 0]


In [25]:
# 3
import numpy as np
a3 = np.random.randint(0,10,size=(4,4))
print(a3)
print(a3[[0,1,3], [0,2,2]])

[[7 6 5 2]
 [7 5 9 8]
 [7 4 6 0]
 [4 5 5 8]]
[7 9 5]


In [26]:
# 4
import numpy as np
a4 = np.random.randint(0,10,size=(4,4))
print(a4)
print(a4[2:4])

[[1 4 4 2]
 [9 2 6 6]
 [2 7 2 0]
 [7 9 8 5]]
[[2 7 2 0]
 [7 9 8 5]]


In [27]:
# 5
import numpy as np
a5 = np.random.randint(0,10,size=(8,9))
print(a5)
print("==" * 20)
aq = a5[1:6, 8]
print(aq)
print(aq[aq > 3])

[[7 8 3 0 6 9 9 4 6]
 [9 8 1 9 5 4 8 9 3]
 [7 2 9 3 2 4 5 9 8]
 [2 8 5 0 4 2 2 9 7]
 [4 7 4 6 6 2 5 2 7]
 [5 7 1 1 8 9 3 3 2]
 [4 4 7 7 3 9 8 7 6]
 [7 5 6 8 0 4 6 7 3]]
[3 8 7 7 2]
[8 7 7]


In [29]:
# 5 答案
conditions = a5[1:6, 8] > 3# 判断条件
print(conditions)
ap = a5[1:6, 8]# 需要进行判断的切片数组
print(ap)
print(ap[conditions])


[False  True  True  True False]
[3 8 7 7 2]
[8 7 7]
